name: arithmetic_parser
description: A simple parser for arithmethic expressions.
version: 1.0.0
authors:
  - Harshal Nandigramwar <pro.bbcom18@gmail.com>
repository: https://github.com/bitbeast18/arithmetic-parser

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
